APB UVM Agent: apb_coverage_monitor Class Reference
apb_coverage_monitor Class Reference
Collects basic functional coverage information observed by an APB agent.
Public Member Functions
uvm_component_utils (apb_coverage_monitor)
covergroup apb_cov ()
Covers that both read and write transactions were observed.
new (string name="apb_coverage_monitor", uvm_component parent=null)
Conventional UVM component constructor.
void write (T t)
Samples coverage on the received transaction.
void report_phase (uvm_phase phase)
Reports collected coverage during the corresponding phase of UVM test execution.
Public Attributes
apb_seq_item analysis_txn
Transaction instance to be covered.
Detailed Description
Collects basic functional coverage information observed by an APB agent.
An instance of the coverage monitor will be part of the agent only if its configuration knob, apb_agent_config::has_functional_coverage, is set.
The coverage monitor extends uvm_subscriber so it can be connected to apb_monitor.
Definition at line 30 of file apb_coverage_monitor.svh.
Member Function Documentation
apb_cov()
covergroup apb_coverage_monitor::apb_cov ()
Covers that both read and write transactions were observed.
Definition at line 42 of file apb_coverage_monitor.svh.
References analysis_txn, apb_seq_item::we, and write().
Referenced by new(), and write().
new()
apb_coverage_monitor::new (string name = "apb_coverage_monitor", uvm_component parent = null)
Conventional UVM component constructor.
Definition at line 90 of file apb_coverage_monitor.svh.
References apb_cov().
report_phase()
void apb_coverage_monitor::report_phase (uvm_phase phase)
Reports collected coverage during the corresponding phase of UVM test execution.
Parameters
phase Reference to the corresponding phase instance.
Definition at line 100 of file apb_coverage_monitor.svh.
uvm_component_utils()
apb_coverage_monitor::uvm_component_utils (apb_coverage_monitor)
write()
void apb_coverage_monitor::write (T t)
Samples coverage on the received transaction.
This method implements the UVM subsciber's observe method.
Parameters
t Transaction on which to sample the coverage.
Definition at line 95 of file apb_coverage_monitor.svh.
References analysis_txn, and apb_cov().
Referenced by apb_cov().
Member Data Documentation
analysis_txn
apb_seq_item apb_coverage_monitor::analysis_txn
Transaction instance to be covered.
This merely a reference to the last transaction received from the APB monitor this coverage monitor instance connects to.
Definition at line 57 of file apb_coverage_monitor.svh.
Referenced by apb_cov(), and write().
The documentation for this class was generated from the following file:
apb_coverage_monitor.svh